name: 'Build and Publish'
description: 'Builds Image and pushes'
inputs:
  targets:
    description: 'Targets'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Login into Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Login into Github Docker Registery
      shell: bash
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push
      uses: docker/bake-action@v6
      with:
        push: true
        targets: ${{ inputs.targets }}
      env:
        imageSuffix: ${{ github.event_name == 'pull_request' && '-ci-test' || '' }}
        tagPrefix: ${{ github.event_name == 'pull_request' && format('{0}-', github.run_id) || '' }}
