name: Build Demo Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - demo/**
      - bake-demo.hcl
  pull_request:
    paths:
      - demo/**
      - bake-demo.hcl

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
    demo:
        name: Demo
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Build
          uses: ./.github/action/build-bake-publish
          with:
            targets: demo
            bake_file: bake-demo.hcl
            docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
            docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
